export class HmRouterPathConstants {
  static readonly PAGE_MAIN_NAV: string = 'MainPage';
  static readonly PAGE_URL_NAV: string = 'NavPage';
  static readonly PAGE_LOGIN_NAV: string = 'LoginMainPage';
  static readonly PAGE_REGISTER_NAV: string = 'RegisterMainPage';
  static readonly PAGE_MINE_NAV: string = 'MineMainPage';
  static readonly PAGE_ARTICLE_DETAIL_NAV: string = 'ArticleDetailPage';
  static readonly PAGE_MINE_INTEGRAL_NAV: string = 'MyIntegralPage';
  static readonly PAGE_MINE_DETAIL_NAV: string = 'MineDetailPage';
  static readonly PAGE_MINE_COLLECTION_NAV: string = 'MyCollectionPage';
  static readonly PAGE_MINE_SHARE_NAV: string = 'MySharePage';
  static readonly PAGE_SETTING_NAV: string = 'MineSettingPage';
  static readonly PAGE_MINE_MESSAGE_NAV: string = 'MyMessagePage';
}