export class UtilConstants {
  static readonly CONST_WIDTH_UI: string = '100%';
  static readonly CONST_HEIGHT_UI: string = '100%';
  static readonly CONST_UI_PER_100: string = '100%';
  static readonly CONST_UI_PER_95: string = '95%';
  static readonly CONST_UI_PER_80: string = '80%';
  static readonly CONST_UI_PER_50: string = '50%';
  static readonly CONST_UI_PER_40: string = '40%';
  static readonly CONST_UI_PER_35: string = '35%';
  static readonly CONST_UI_PER_30: string = '30%';
  static readonly CONST_UI_PER_10: string = '10%';
  static readonly CONST_UI_PER_8: string = '8%';
  static readonly CONST_UI_PER_3: string = '3%';
  static readonly CONST_UI_AUTO: string = 'auto';
  // size vp
  static readonly CONST_UI_SIZE_300: number = 300;
  static readonly CONST_UI_SIZE_150: number = 150;
  static readonly CONST_UI_SIZE_100: number = 100;
  static readonly CONST_UI_SIZE_95: number = 95;
  static readonly CONST_UI_SIZE_80: number = 80;
  static readonly CONST_UI_SIZE_76: number = 76;
  static readonly CONST_UI_SIZE_64: number = 64;
  static readonly CONST_UI_SIZE_56: number = 56;
  static readonly CONST_UI_SIZE_50: number = 50;
  static readonly CONST_UI_SIZE_48: number = 48;
  static readonly CONST_UI_SIZE_45: number = 45;
  static readonly CONST_UI_SIZE_40: number = 40;
  static readonly CONST_UI_SIZE_35: number = 35;
  static readonly CONST_UI_SIZE_32: number = 32;
  static readonly CONST_UI_SIZE_28: number = 28;
  static readonly CONST_UI_SIZE_25: number = 25;
  static readonly CONST_UI_SIZE_24: number = 24;
  static readonly CONST_UI_SIZE_22: number = 22;
  static readonly CONST_UI_SIZE_20: number = 20;
  static readonly CONST_UI_SIZE_15: number = 15;
  static readonly CONST_UI_SIZE_13: number = 13;
  static readonly CONST_UI_SIZE_10: number = 10;
  static readonly CONST_UI_SIZE_8: number = 8;
  static readonly CONST_UI_SIZE_6: number = 6;
  static readonly CONST_UI_SIZE_5: number = 5;
  static readonly CONST_UI_SIZE_3: number = 3;
  static readonly CONST_UI_SIZE_2: number = 2;
  static readonly CONST_UI_SIZE_1: number = 1;
  static readonly CONST_UI_SIZE_DIVIDER: number = 0.5;
  static readonly CONST_UI_SIZE_NEG_10: number = -10;
  // font size fp
  static readonly CONST_UI_FONT_SIZE_10: number = 10;
  static readonly CONST_UI_FONT_SIZE_13: number = 13;
  static readonly CONST_UI_FONT_SIZE_14: number = 14;
  static readonly CONST_UI_FONT_SIZE_15: number = 15;
  static readonly CONST_UI_FONT_SIZE_16: number = 16;
  static readonly CONST_UI_FONT_SIZE_18: number = 18;
  static readonly CONST_UI_FONT_SIZE_20: number = 20;
  static readonly CONST_UI_FONT_SIZE_22: number = 22;
  static readonly CONST_UI_FONT_SIZE_30: number = 30;
  // color
  static readonly CONST_UI_COLOR_F3F4F5: string = '#F3F4F5';
  static readonly CONST_UI_COLOR_67bc5e: string = '#67bc5e';
  static readonly CONST_UI_COLOR_24246c: string = '#24246c';
  static readonly CONST_UI_COLOR_white: string = '#FFFFFF';
  static readonly CONST_UI_COLOR_black: string = '#000000';
  static readonly CONST_UI_COLOR_0D000000: string = '#0D000000';
  static readonly CONST_UI_COLOR_66000000: string = '#66000000';
  static readonly CONST_UI_COLOR_99000000: string = '#99000000';
  static readonly CONST_UI_COLOR_999999: string = '#999999';
  static readonly CONST_UI_COLOR_f6f7f6: string = '#f6f7f6';
  // font weight
  static readonly CONST_UI_FONT_WEIGHT_700: number = 700;
  static readonly CONST_UI_FONT_WEIGHT_400: number = 400;
  // page size
  static readonly CONST_PAGE_SIZE: number = 15;
  // pullToRefresh
  static readonly CONST_PULL_HINT: string = '刷新成功';
  static readonly CONST_PULL_DOWN_HINT: string = '刷新中...';
  static readonly CONST_LOAD_HINT: string = '加载更多';
  static readonly CONST_LOADING_HINT: string = '数据加载中...';
  static readonly CONST_LOAD_END_HINT: string = '数据到底啦';
  // Breakpoint
  static readonly CONST_BREAKPOINT_XS: string = 'xs';
  static readonly CONST_BREAKPOINT_SM: string = 'sm';
  static readonly CONST_BREAKPOINT_MD: string = 'md';
  static readonly CONST_BREAKPOINT_LG: string = 'lg';
  static readonly CONST_BREAKPOINT_XL: string = 'xl';
  // WidthBreakpoint
  static readonly CONST_WIDTH_BREAKPOINT_XS: number = 320;
  static readonly CONST_WIDTH_BREAKPOINT_SM: number = 600;
  static readonly CONST_WIDTH_BREAKPOINT_LG: number = 840;
  static readonly CONST_WIDTH_BREAKPOINT_XL: number = 1440;
  // HeightBreakpoint
  static readonly CONST_HEIGHT_BREAKPOINT_RATIO_0: number = 0.8;
  static readonly CONST_HEIGHT_BREAKPOINT_RATIO_1: number = 1.2;
  // column
  static readonly COLUMN_SM: number = 4;
  static readonly COLUMN_MD: number = 8;
  static readonly COLUMN_LG: number = 12;
  // span
  static readonly SPAN_SM: number = 4;
  static readonly SPAN_MD: number = 6;
  static readonly SPAN_LG: number = 8;
  // offset
  static readonly OFFSET_SM: number = 0;
  static readonly OFFSET_MD: number = 1;
  static readonly OFFSET_LG: number = 2;
  //duration
  static readonly EXIT_APP_DURATION: number = 1500;
  // HMRouter
  static readonly LIFECYCLE_EXIT_APP: string = 'ExitAppLifecycle';
  static readonly HMROUTER_INTERCEPTOR: string = 'LoginCheckInterceptor';
  // DialogHub
  static readonly LOGOUT: string = "退出登录";
  static readonly LOGOUT_TIPS: string = "是否要确定退出当前账号";
  static readonly CANCEL: string = "取消";
  static readonly OUT: string = "退出";
  // refresh
  static readonly REFRESH_OFFSET_TOTAL: number = 64;
}