export interface ArticleInfo {
  adminAdd:boolean,
  apkLink:string,
  audit:number,
  author: string,
  canEdit:boolean,
  chapterId: number,
  chapterName: string,
  courseId: number,
  desc: string,
  descMd:string,
  envelopePic: string,
  fresh:boolean,
  host:string,
  id: number,
  isAdminAdd:boolean,
  link: string,
  niceDate: string,
  niceShareDate: string,
  origin: string,
  prefix: string,
  projectLink: string,
  publishTime: number,
  realSuperChapterId: number,
  selfVisible: number,
  shareDate: number,
  shareUser: string,
  superChapterId: number,
  superChapterName: string,
  tags: [],
  title: string,
  type: number,
  userId: number,
  visible: number,
  zan: number,
}

export interface CoinInfo {
  coinCount: number;
  level: number;
  desc: string;
  rank: string;
  userId: number;
  userName: string;
}

export interface ArticleInfoData {
  curPage: number;
  datas: ArticleInfo[];
  offset: number;
  over: boolean;
  pageCount: number;
  size: number;
  total: number;
}

export interface ShareInfoData{
  shareArticles: ArticleInfoData;
  coinInfo: CoinInfo;
}

export interface ShareArticleResponse {
  data: ShareInfoData;
  errorCode: number;
  errorMsg: string;
}